version: 1
disable_existing_loggers: True

root:
  level: WARNING
  handlers: [console, file]

loggers:
  coinbitrage:
    level: DEBUG
    handlers: [console, file, order]
    propagate: False

formatters:
  simple:
    (): coinbitrage.bitlogging.BitLogFormatter
    format: '{asctime}  {levelname:8} {message}'
    datefmt: '%Y-%m-%d %H:%M:%S (%Z)'
    as_utc: False
    style: '{'
  json:
    (): coinbitrage.bitlogging.JSONFormatter
    datefmt: '%Y-%m-%dT%H:%M:%S.%f%z'
  order:
    (): coinbitrage.bitlogging.OrderFormatter

filters:
  order_filter:
    (): coinbitrage.bitlogging.EventNameFilter
    contains: 'order'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    when: midnight
    formatter: json
    level: DEBUG
  order:
    class: logging.handlers.TimedRotatingFileHandler
    when: midnight
    formatter: json
    filters: [order_filter]
    level: INFO
