version: 1
disable_existing_loggers: True

root:
  level: WARNING
  handlers: [console, file]

loggers:
  coinbitrage:
    level: DEBUG
    handlers: [console, file, order]
    propagate: False

formatters:
  simple:
    format: '{asctime} {levelname:8} {message}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'
  detail:
    format: '{asctime} {levelname:8} {name} ({threadName}): {message} -- {event_name} {event_data}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'
  order:
    (): coinbitrage.bitlogging.OrderFormatter.create

filters:
  order_filter:
    (): coinbitrage.bitlogging.OrderFilter.create

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    when: midnight
    formatter: detail
    level: DEBUG
  order:
    class: logging.handlers.TimedRotatingFileHandler
    when: midnight
    formatter: order
    filters: [order_filter]
    level: INFO
